name: dual_image_picker
description: "A Flutter package that provides a customizable image picker widget, allowing users to select images from the gallery or capture them using the camera."
version: 0.2.2
homepage: https://github.com/919Umesh/custom_image_picker


environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.dual_image_picker
        pluginClass: CustomImagePickerPlugin


